# 사전 조사된 대학별 AI 서비스 정보
# (공식 발표 여부, 생성형 AI 모델, 도입 플랫폼, AI 활용 분야, 파트너/업체)
# 중앙일보 2025 대학평가 TOP 30 기준 (2026-03 기준)

AI_KNOWLEDGE_DB = {
    "서울대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT, Gemini, Cursor AI 등 멀티LLM",
        "platform": "구축 중 (33.6억 원 규모)",
        "application_area": "교육·연구·행정 맞춤 AI 에이전트",
        "partner": "KT·네이버클라우드·OpenAI",
        "policy_url": "https://now.snu.ac.kr/category/3/353",
    },
    "연세대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT, Claude, Gemini 등 외부 도구",
        "platform": "전용 플랫폼 없음",
        "application_area": "교육 실습·연구 윤리·Google AI Policy Campus",
        "partner": "Google·NVIDIA·삼성·SKT·KT·LGU+",
        "policy_url": "https://digitalint.yonsei.ac.kr/board/notice.php?mNum=4&sNum=1&boardid=notice&mode=view&idx=6",
    },
    "한양대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT 등 외부 도구",
        "platform": "카카오톡 챗봇·AI 가이드 페이지",
        "application_area": "교수학습 가이드라인·학과AI교육인증제",
        "partner": "-",
        "policy_url": "http://chatbot.hanyang.ac.kr/ko",
    },
    "고려대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT 중심 외부 도구",
        "platform": "전용 플랫폼 없음",
        "application_area": "학부교육·연구 가이드라인 배포",
        "partner": "-",
        "policy_url": "https://ini.korea.ac.kr/guidelines/",
    },
    "성균관대학교": {
        "official_status": "✅",
        "ai_model": "KingoGPT (GPT-5·Azure OpenAI 기반)",
        "platform": "KingoGPT (Microsoft Azure)",
        "application_area": "수업자료 자동화·번역·RAG 문서검색·행정",
        "partner": "Microsoft Azure",
        "policy_url": "https://www.etnews.com/20251105000130",
    },
    "경희대학교": {
        "official_status": "✅",
        "ai_model": "GPT-5.1 기본, OpenAI·Google·Anthropic 선택",
        "platform": "ChatKHU(챗쿠) (2026-02 정식 오픈)",
        "application_area": "교육·연구·행정 통합 AI 서비스, 노코드 챗봇 Studio",
        "partner": "DX추진단 자체 구축",
        "policy_url": "https://media.khu.ac.kr/bbs/board.php?bo_table=univJubo&wr_id=38636",
    },
    "이화여자대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT 등 외부 도구",
        "platform": "THE BEST 포털 AI 가이드 (전용 플랫폼 없음)",
        "application_area": "연구자용 생성형 AI 가이드라인·AI 대학 신설·진로지원",
        "partner": "Elsevier (AI 신약연구 MOU)",
        "policy_url": "https://eips.ewha.ac.kr/eips/board/notice.do?mode=view&articleNo=772842",
    },
    "건국대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT 기반 AI KU 챗봇, COVI AI 코딩",
        "platform": "AI KU 챗봇, COVI AI 코딩 플랫폼",
        "application_area": "학생 챗봇·AI 코딩 교육·Dr.KU AI 튜터",
        "partner": "미림미디어랩",
        "policy_url": "https://www.konkuk.ac.kr/bbs/konkuk/240/1156512/artclView.do",
    },
    "동국대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT (OpenAI)",
        "platform": "전용 플랫폼 없음",
        "application_area": "수업·과제 활용 가이드, AX 2026-2030 계획",
        "partner": "-",
        "policy_url": "https://engineer.dongguk.edu/article/notice1/detail/179641",
    },
    "중앙대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT 등 외부 도구",
        "platform": "생성형 AI 안내 전용 사이트 (aiguide.cau.ac.kr)",
        "application_area": "수업 AI 활용 허용·제한·금지 3단계 분류 체계",
        "partner": "-",
        "policy_url": "https://aiguide.cau.ac.kr/",
    },
    "서강대학교": {
        "official_status": "✅",
        "ai_model": "GPT-4.1, Gemini, Claude 등 멀티LLM",
        "platform": "FactChat (마인드로직), Pulley Campus, ALLO",
        "application_area": "교육·연구·AI 표절 탐지(Turnitin)",
        "partner": "마인드로직·NC AI·Upstage·NotaAI",
        "policy_url": "https://www.sogang.ac.kr/ko/detail/548353",
    },
    "인하대학교": {
        "official_status": "✅",
        "ai_model": "다양한 모델 (멀티LLM)",
        "platform": "인하 인공지능 플랫폼 (몬드리안 AI 협력)",
        "application_area": "연구·교육 AI 실험, AI 역량 강화 프로그램",
        "partner": "몬드리안 AI",
        "policy_url": "https://aix.inha.ac.kr/?page_id=4406&vid=1",
    },
    "한양대학교 ERICA": {
        "official_status": "✅",
        "ai_model": "한양대학교 가이드라인 준용",
        "platform": "ERICA AI융합연구소 (전용 플랫폼 없음)",
        "application_area": "AI 기반 물류·AI 융합 산학협력",
        "partner": "노블로지스 등 산학",
        "policy_url": "https://www.hanyang.ac.kr/official-press",
    },
    "국민대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT, Perplexity, Gemini, DALL-E 3 등",
        "platform": "전용 플랫폼 없음",
        "application_area": "AI 윤리강령(2023)·6원칙 가이드라인",
        "partner": "-",
        "policy_url": "https://research.kookmin.ac.kr/information/promotion/1259",
    },
    "아주대학교": {
        "official_status": "✅",
        "ai_model": "다양한 생성형 AI 도구",
        "platform": "전용 플랫폼 없음",
        "application_area": "수업 AI 활용 가이드라인 (금지·제한·자유 3단계)",
        "partner": "-",
        "policy_url": "https://press.ajou.ac.kr/news/articleView.html?idxno=11303",
    },
    "서울시립대학교": {
        "official_status": "✅",
        "ai_model": "멀티LLM (통합 LLM 플랫폼 기반)",
        "platform": "AIChat (2026-01 본격 개시)",
        "application_area": "교육·연구·행정 수요 대응, 첨단 수업환경 구축",
        "partner": "-",
        "policy_url": "https://news.unn.net/news/articleView.html?idxno=587825",
    },
    "한국외국어대학교": {
        "official_status": "⚠️ 부분",
        "ai_model": "외부 도구 활용",
        "platform": "전용 플랫폼 없음",
        "application_area": "AI융합대학 신설(2026학년도), Language & AI 융합학부",
        "partner": "-",
        "policy_url": "https://www.hufs.ac.kr",
    },
    "서울과학기술대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT 등 외부 도구",
        "platform": "전용 플랫폼 없음",
        "application_area": "ChatGPT 활용 역량 강화 프로그램, AI 실습 교육",
        "partner": "-",
        "policy_url": "https://seoultech.ac.kr/service/info/notice?do=commonview&bnum=4691&bidx=561765",
    },
    "세종대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT 등 외부 도구",
        "platform": "전용 플랫폼 없음",
        "application_area": "생성형 AI 가이드라인 제정(2023), 교수-학습 기본 활용 가이드, 학술정보원 LibGuide",
        "partner": "-",
        "policy_url": "https://pr.sejong.ac.kr/news/newsletter/news.do?mode=view&articleNo=799289",
    },
    "숙명여자대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT, Gemini, Perplexity 등 멀티LLM",
        "platform": "FactChat (2025-12 시범 개시)",
        "application_area": "교육·연구 AI 서비스, AI 윤리 3원칙 체계",
        "partner": "마인드로직",
        "policy_url": "https://www.sookmyung.ac.kr/kr/etc/privacy-list.do?mode=view&articleNo=91449",
    },
    "경북대학교": {
        "official_status": "✅",
        "ai_model": "멀티LLM (다양한 모델)",
        "platform": "생성형 AI 안내사이트 (aiguide.knu.ac.kr), AI 기반 플랫폼 구축 중",
        "application_area": "교육·연구 AI 지원, AI 디지털 융합교육 확산",
        "partner": "-",
        "policy_url": "https://aiguide.knu.ac.kr/",
    },
    "부산대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT, Gemini, Claude 등 (하이브리드)",
        "platform": "산지니 AI (온프레미스+클라우드 하이브리드)",
        "application_area": "교육·연구·행정 전 영역, AI 정책표준 수립(국내 최초)",
        "partner": "자체 구축 (AX·정보화혁신본부)",
        "policy_url": "https://www.pusan.ac.kr/kor/CMS/Board/Board.do?mCode=MN114&mode=view&mgr_seq=16&board_seq=1507686",
    },
    "가톨릭대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT 등 외부 도구",
        "platform": "생성형 AI LibGuide, AI 기반 학습 플랫폼(Covi 연동)",
        "application_area": "AI 활용 교과목 지원사업, AI 윤리 특강",
        "partner": "-",
        "policy_url": "https://www.catholic.ac.kr/ko/campuslife/notice.do?mode=view&articleNo=268506",
    },
    "광운대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT, Claude, Gemini 등",
        "platform": "FactChat 시범운영(2025-11)",
        "application_area": "AI 활용 교육, AI 석사과정 신설",
        "partner": "마인드로직",
        "policy_url": "https://www.kw.ac.kr/ko/life/notice.jsp?BoardMode=view&DUID=51161",
    },
    # ── 중앙일보 TOP 30 추가 6개 대학 ──────────────────────────────────────
    "가천대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT 등 외부 도구",
        "platform": "전용 플랫폼 없음",
        "application_area": "수업·과제·시험 AI 단계적 허용, AI 기초교양 필수(4-8학점), AI 통합 강좌 208개(2025)",
        "partner": "-",
        "policy_url": "https://www.gachon.ac.kr/bbs/eng/1437/117556/artclView.do",
    },
    "전북대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT, Gemini, Perplexity, Claude, Grok, Llama, Gemma, Solar 등 멀티LLM",
        "platform": "멀티LLM 기반 생성형 AI 시범 서비스",
        "application_area": "교육·학습, 가이드라인 전면 개정(2025-12, 금지·부분허용·전면허용 3단계)",
        "partner": "-",
        "policy_url": "https://www.jbnu.ac.kr/web/Board/196551/detailView.do",
    },
    "인천대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT Team 등",
        "platform": "ChatGPT Team 시범 지원(2025-07), UNIAI 교육지원 시스템",
        "application_area": "교수 연구·교육 지원, 보안 가이드라인·체크리스트 배포",
        "partner": "OpenAI (ChatGPT Team)",
        "policy_url": "https://inu.ac.kr/inu/13580/subview.do",
    },
    "충남대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT, Gemini, Claude, Gemma, xAI, Llama, Perplexity 등 57종",
        "platform": "CNU AI+ (aiedu.cnu.ac.kr) + 멀티LLM 서비스(2026-03 전면 개방)",
        "application_area": "교육·연구·행정 통합, LMS 내 AI 활용 서약 체크리스트 의무화",
        "partner": "자체 구축",
        "policy_url": "https://plus.cnu.ac.kr/_prog/_board/?code=sub07_0703&mode=V&no=2512070",
    },
    "숭실대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT, Gemini 등 멀티LLM (FactChat)",
        "platform": "FactChat (ssu.factchat.bot), 2025-09부터 전 구성원 무상 제공",
        "application_area": "교육·연구 전 영역, AI 네이티브 대학 선언, AI 단과대학 신설",
        "partner": "마인드로직",
        "policy_url": "https://www.joongang.co.kr/article/25364063",
    },
    "전남대학교": {
        "official_status": "✅",
        "ai_model": "ChatGPT, Gemini, Perplexity, Claude, Grok, Llama, Mistral, Qwen 8종",
        "platform": "8종 멀티LLM 무료 제공 (2025-12-15 개시, KT MOU 기반)",
        "application_area": "교육·연구·행정 전반 AI 전환, AI 윤리 가이드라인 구축 중",
        "partner": "KT (글로컬대학 MOU)",
        "policy_url": "https://www.yna.co.kr/view/AKR20251214024400054",
    },
}
